### ISSUE TITLE
Problem Installing Example Project

### ISSUE THREAD

**Issue by paulovsm** [Seanalair/GreenAR#1]
Hi, I tried to install the example project following the instructions `clone the repo, and run pod install from the Example directory first.`. However, when I tried to run the project from XCode the build failed due the following errors:

```
Signing Error: No account for team "6AW353N549". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
Code Signing Error: No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "6AW353N549" with a private key was found.
Code Signing Error: Code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 11.0'
```

The account isn't my account number, what it could be?

**Comment by Seanalair** [comment]
You need to switch the developer account to your own in order to be able to run the project from xcode. Open up the settings for the project and change the “team” shown there to the one for your developer account.

**Comment by paulovsm** [comment]
I did exactly that. I opened the GreenAR's  General settings tab and change to my Dev account in the Signing section.

I just realized that the error happens in GreenAR_Tests component.

**Comment by Seanalair** [comment]
So the problem is solved? You updated the team selected in each target, and were able to install the example project?

**Comment by paulovsm** [comment]
Sorry my fault, i did not realized that there was more than one target. I changed both targets and now I could build the app. Thanks.

**Comment by Seanalair** [comment]
Glad to help.  I've only very recently started work on this library; I'm surprised you found it already. Good luck on your project! Feel free to reach out and let me know what you think of the library so far.
